/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynatrace_diagnostics_sdk_io_LZOCompression */

#ifndef _Included_com_dynatrace_diagnostics_sdk_io_LZOCompression
#define _Included_com_dynatrace_diagnostics_sdk_io_LZOCompression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_init
  (JNIEnv *, jclass);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    getMaxInSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_getMaxInSize
  (JNIEnv *, jclass);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    getMaxOutSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_getMaxOutSize
  (JNIEnv *, jclass);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    compress
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_compress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    decompress
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_decompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    decompressSafe
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_decompressSafe
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    dynMemCompress
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_dynMemCompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    dynMemDecompress
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_dynMemDecompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_dynatrace_diagnostics_sdk_io_LZOCompression
 * Method:    dynMemDecompressSafe
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynatrace_diagnostics_sdk_io_LZOCompression_dynMemDecompressSafe
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
